name: Builds and Tests

on: [pull_request]

jobs:
  format-go:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Go formatting
        run: |
            [ "$(gofmt -l .)" = "" ] || (gofmt -d . && exit 1)

  tidy-go:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
        id: go
      - name: CHeckout
        uses: actions/checkout@v2
      - name: Check go mod tidy
        # Use --check or --exit-code when available (Go 1.19?)
        # https://github.com/golang/go/issues/27005
        run: |
            go mod tidy
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi

  format-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
        id: go
      - name: Install shfmt
        run: GO111MODULE=on go install mvdan.cc/sh/v3/cmd/shfmt@v3.4.0
      - name: Run shfmt
        run: shfmt -d .

  lint-scripts:
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: |
            sudo apt update
            sudo apt install -y git shellcheck
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run shellcheck
        run: ./devtools/check_shellscript_lint.sh
