name: Deploy to Git

on:
  push:
    branches:
      - get_assets

permissions:
  pull-requests: write
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-releases:
    name: Update releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: cd builders && make docker-image-alpine && make docker-image-cross
      - name: Build & Test static library
        run: make release-build-alpine
      - name: Build static library for MacOS
        run: make release-build-macos-static
      - name: Collect artifacts
        run: |
          mkdir artifacts
          cp ./internal/api/libwasmvm_muslc.a ./artifacts/libwasmvm_muslc.x86_64.a
          cp ./internal/api/libwasmvm_muslc.aarch64.a ./artifacts/libwasmvm_muslc.aarch64.a
          cp ./internal/api/libwasmvmstatic_darwin.a ./artifacts/libwasmvmstatic_darwin.a
      - name: Create checksums
        run: |
          cd ./artifacts
          sha256sum * > checksums.txt && cat checksums.txt
          cd ../
      - name: Upload shared library
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./artifacts/*
