name: Builds and Tests

on:
  pull_request:
    type:
      - closed

jobs:
  deploy_to_git:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: Make changes
    #     run: touch test.txt
    #   - name: commit
    #     run: |
    #       CURRENT_BRANCH="${GITHUB_HEAD_REF}-update-shared-library"
    #       echo $CURRENT_BRANCH
    #       git config user.name  "github-actions[bot]"
    #       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #       git add .
    #       git commit -m "auto generate shared library"
    #   - name: auto
    #     run: |
    #       gh pr list
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   deploy_to_git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make changes
        run: touch test.txt
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs 
      # - name: test
      #   run: |
      #     git config user.name  "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "auto generate shared library"
      - name: Create pull request
        id: cpr 
        uses: peter-evans/create-pull-request@v5
        with:
          # token: ${{ secrets.MACHINE_USER_PAT }}
          # push-to-fork: 170210/wasmvm
          commit-message: "chore: update shared library"
          committer: GitHub <noreply@github.com>
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          signoff: true
          branch: "${GITHUB_HEAD_REF}_shared_library_test"
          #_${{ github.sha }}
          delete-branch: true
          title: 'chore: update shared library'
          body: |
            # Description
            Update shared library
            - Updated shared library
            - This is caused by #${{ github.event.pull_request.number }}"
            - Auto-generated by [create-pull-request][1]

            ## Types of changes
            - [ ] Bug fix (changes which fixes an issue)
            - [ ] New feature (changes which adds functionality)
            - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
            - [x] ETC (build, ci, docs, perf, refactor, style, test)

            ## Checklist
            - [x] I followed the [contributing guidelines](https://github.com/Finschia/wasmvm/blob/main/CONTRIBUTING.md).
            - [ ] I have updated the documentation accordingly.
            - [ ] I have added tests to cover my changes.
            - [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automerge
          # assignees: 170210
          # reviewers: 170210
          # team-reviewers: |
          #   developers
          #   qa-team
          # milestone: 1
          draft: false
