name: Builds and Tests

on:
  pull_request:
    type:
      - closed

jobs:
  deploy_to_git:
    runs-on: ubuntu-latest
    needs: build_shared_library
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make changes
        run: touch test.txt
      - name: commit
        run: |
          CURRENT_BRANCH="${GITHUB_BASE_REF}-update-shared-library"
          echo $CURRENT_BRANCH
          git add .
          git commit -m "test"
      - name: auto
        run: |
          gh pr list