name: Builds and Tests

on:
  pull_request:
    type:
      - closed

jobs:
  deploy_to_git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make changes
        run: touch test.txt
      - name: commit
        run: |
          CURRENT_BRANCH="${GITHUB_HEAD_REF}-update-shared-library"
          echo $CURRENT_BRANCH
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto generate shared library"
      - name: auto
        run: |
          gh pr list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
